services:
  redis:
    image: redis:7.4.1
    container_name: redis
    restart: always
    env_file: .env.redis
    networks:
      - mern-app
    command: ['redis-server', '--requirepass', '${PASSWORD}']
  server:
    image: doankietdev/digital-world-shop-api:1.0.0
    env_file:
      - .env.server
    environment:
      - NODE_ENV=prod
    depends_on:
      - redis
    networks:
      - mern-app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot --webroot-path /var/www/certbot/ --dry-run -d digitals.software

  client:
    image: doankietdev/digital-world-shop-web:1.0.0
    env_file: .env.client
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot/:ro
    depends_on:
      - server
      - certbot
    networks:
      - mern-app

networks:
  mern-app:
    driver: bridge
