services:
  redis:
    image: redis:7.4.1
    container_name: redis
    restart: always
    env_file: .env.redis
    networks:
      - mern-app
    command: ['redis-server', '--requirepass', '${PASSWORD}']
  server:
    image: doankietdev/digital-world-shop-api:1.0.0
    env_file:
      - .env.server
    environment:
      - NODE_ENV=prod
    networks:
      - mern-app

  client:
    image: doankietdev/digital-world-shop-web:1.0.0
    env_file: .env.client
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - mern-app

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email doankietdev@gmail.com -d digitals.software --agree-tos
networks:
  mern-app:
    driver: bridge
